#!/bin/sh

choices="Dotfiles\nGitHub\nSuckless\nYouTube" 
chosen=$(echo -e "$choices" | dmenu -p "surf bookmarks" -c -l 10)
w=""
case "$chosen" in
    ""       )                                                      ;;
    Dotfiles ) w="https://www.github.com/Sebastian-Soto-M/dotfiles" ;;
    GitHub   ) w="https://www.github.com"                           ;;
    Suckless ) w="https://www.suckless.org"                         ;;
    YouTube  ) w="https://www.youtube.com"                          ;;
esac
[ ! -z "$w" ]  && surf $w
