#!/bin/sh

choices="alias\ndmenu\np10k\npicom\npolybar\nncspot\nsxhkd\nscripts\nst\
\ntaskrc\ntmux\nneovim\nxinit\nxresources\nzshenv\nzshrc\
\ndm_prompt\ndm_power_manager\nedit menu"

chosen=$(echo -e "$choices" | dmenu -c -l 20)

case "$chosen" in
    ""               )                                                             ;;

    dmenu            ) st -d "$XDG_CONFIG_HOME/dmenu"                              ;;
    neovim           ) st -d "$XDG_CONFIG_HOME/nvim"                               ;;
    st               ) st -d "$XDG_CONFIG_HOME/st"                                 ;;
    scripts          ) st -d "$XDG_CONFIG_HOME/scripts"                            ;;

    alias            ) st -e dash -c "nvim $ZDOTDIR/alias.zsh"                     ;;
    dm_power_manager ) st -e dash -c "nvim $HOME/.config/scripts/dm_power_manager" ;;
    dm_prompt        ) st -e dash -c "nvim $HOME/.config/scripts/dm_prompt"        ;;
    ncspot           ) st -e dash -c "nvim $HOME/.config/ncspot/config.toml"       ;;
    p10k             ) st -e dash -c "nvim $ZDOTDIR/.p10k.zsh"                     ;;
    picom            ) st -e dash -c "nvim $HOME/.config/picom/picom.conf"         ;;
    polybar          ) st -e dash -c "nvim $XDG_CONFIG_HOME/polybar/config"        ;;
    sxhkd            ) st -e dash -c "nvim $HOME/.config/sxhkd/sxhkdrc"            ;;
    taskrc           ) st -e dash -c "nvim $TASKRC"                                ;;
    tmux             ) st -e dash -c "nvim $XDG_CONFIG_HOME/tmux/tmux.conf"        ;;
    xinit            ) st -e dash -c "nvim $XINITRC"                               ;;
    xresources       ) st -e dash -c "nvim ~/.Xresources"                          ;;
    zshenv           ) st -e dash -c "nvim $HOME/.zshenv"                          ;;
    zshrc            ) st -e dash -c "nvim $ZDOTDIR/.zshrc"                        ;;

    *                ) st -e dash -c "nvim $HOME/.config/scripts/dm_dotfiles"      ;;
esac
