#!/bin/sh

choices="Shutdown\nReboot\nSuspend\nLock"

chosen=$(echo -e "$choices" | dmenu -n 3 -c -l 20)

case "$chosen" in
    "Shutdown" ) dm_prompt  "Do you want to shut down?"  "shutdown now"                                        ;;
    "Reboot"   ) dm_prompt  "Do you want to reboot?"     "reboot"                                              ;;
    "Suspend"  ) dm_in      "sudo -A $(systemctl suspend)"                                                     ;;
    "Lock"     ) dm_prompt  "Do you want to lock?"       "qdbus org.freedesktop.ScreenSaver /ScreenSaver Lock" ;;
    *          )                                                                                               ;;
esac
