#!/bin/sh

choices="YouTube\nDotfiles\nGitHub" 
chosen=$(echo -e "$choices" | dmenu -p "surf browser" -c -l 10)
w=""
case "$chosen" in
    ""       )                                                      ;;
    Dotfiles ) w="https://www.github.com/Sebastian-Soto-M/dotfiles" ;;
    YouTube  ) w="https://www.youtube.com"                          ;;
    GitHub   ) w="https://www.github.com"                           ;;
    *        ) w="https://www.google.com/search?q=${chosen}"        ;;
esac
[ ! -z "$w" ]  && surf $w
