#!/bin/sh
configs="ncspot\npicom\npolybar\nsxhkd\ntaskrc\ntmux"
folders="dmenu\nneovim\nscripts\nst\nsurf\nsxiv"
scripts="ask_pass\nbookmark_surf\ndef_install\ndotfiles_dm\nedit menu\ninput_dm\ninput_validation_dm\npmanager_dm\nsearch_surf"
shell="alias\np10k\nzshrc\nzshenv"
xorg="xinitrc\nxresources"

case "$(echo -e "${folders}\n${scripts}\n${configs}\n${shell}\n${xorg}" | dmenu -c -l 10)" in
    # terminal dirs
    dmenu               ) st -d "$XDG_CONFIG_HOME/dmenu"                           ;;
    neovim              ) st -d "$XDG_CONFIG_HOME/nvim"                            ;;
    scripts             ) st -d "$XDG_CONFIG_HOME/scripts"                         ;;
    st                  ) st -d "$XDG_CONFIG_HOME/st"                              ;;

    # configs
    polybar             ) st -e dash -c "nvim $XDG_CONFIG_HOME/polybar/config"     ;;
    tmux                ) st -e dash -c "nvim $XDG_CONFIG_HOME/tmux/tmux.conf"     ;;
    ncspot              ) st -e dash -c "nvim $XDG_CONFIG_HOME/ncspot/config.toml" ;;
    picom               ) st -e dash -c "nvim $XDG_CONFIG_HOME/picom/picom.conf"   ;;
    sxhkd               ) st -e dash -c "nvim $XDG_CONFIG_HOME/sxhkd/sxhkdrc"      ;;
    taskrc              ) st -e dash -c "nvim $TASKRC"                             ;;

    # zsh
    alias               ) st -e dash -c "nvim $ZDOTDIR/alias.zsh"                  ;;
    p10k                ) st -e dash -c "nvim $ZDOTDIR/.p10k.zsh"                  ;;
    zshrc               ) st -e dash -c "nvim $ZDOTDIR/.zshrc"                     ;;
    zshenv              ) st -e dash -c "nvim $HOME/.zshenv"                       ;;

    # scripts
    ask_pass            ) st -e dash -c "nvim $SCRIPTS/ask_pass"                   ;;
    bookmark_surf       ) st -e dash -c "nvim $SCRIPTS/bookmark_surf"              ;;
    def_install         ) st -e dash -c "nvim $SCRIPTS/def_install"                ;;
    input_dm            ) st -e dash -c "nvim $SCRIPTS/input_dm"                   ;;
    input_validation_dm ) st -e dash -c "nvim $SCRIPTS/input_validation_dm"        ;;
    pmanager_dm         ) st -e dash -c "nvim $SCRIPTS/pmanager_dm"                ;;
    search_surf         ) st -e dash -c "nvim $SCRIPTS/search_surf"                ;;
    "edit menu"         ) st -e dash -c "nvim $SCRIPTS/dotfiles_dm"                ;;

    # xorg
    xinit               ) st -e dash -c "nvim $XINITRC"                            ;;
    xresources          ) st -e dash -c "nvim $HOME/.Xresources"                   ;;

    # default
    *                   )                                                          ;;
esac
