#!/bin/sh

alias config='/usr/bin/git --git-dir=$HOME/.config/dotfiles --work-tree=$HOME'
git clone --bare git@github.com:Sebastian-Soto-M/dotfiles.git $HOME/.config/dotfiles
echo "Remember to run config checkout to pull the dotfiles (this may require you to delete some existing files)"

#zsh
sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
git clone git@github.com:svenXY/timewarrior ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/timewarrior
git clone --depth=1 git@github.com:romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
git clone https://github.com/zdharma/fast-syntax-highlighting.git \
  ~ZSH_CUSTOM/plugins/fast-syntax-highlighting

#suckless
git clone git@github.com:Sebastian-Soto-M/dmenu.git ~/.config/dmenu
cd ~/.config/dmenu && sudo make clean install

git clone git@github.com:Sebastian-Soto-M/dwm.git ~/.config/dwm
cd ~/.config/dwm && sudo make clean install

git clone git@github.com:Sebastian-Soto-M/st.git ~/.config/st
cd ~/.config/st && sudo make clean install

git clone git@github.com:Sebastian-Soto-M/surf.git ~/.config/dwm
cd ~/.config/surf && sudo make clean install

git clone git@github.com:Sebastian-Soto-M/sxiv.git ~/.config/sxiv
cd ~/.config/sxiv && sudo make clean install

#tmux
git clone git@github.com:tmux-plugins/tpm ~/.config/tmux/plugin_manager/plugins/tpm

## SDKMAN

