#!/bin/sh
git clone git@github.com:Sebastian-Soto-M/dmenu.git ~/.config/dmenu
git clone git@github.com:Sebastian-Soto-M/dwm.git ~/.config/dwm
git clone git@github.com:Sebastian-Soto-M/st.git ~/.config/st
git clone git@github.com:Sebastian-Soto-M/surf.git ~/.config/surf
git clone git@github.com:Sebastian-Soto-M/sxiv.git ~/.config/sxiv

pushd ~/.config
cd dmenu
cd ..
cd dwm
cd ..
cd st
cd ..
cd surf
cd ..
cd sxiv
cd
