#!/bin/sh
function web_script() {
    read -p "$1 $2 [y/n]: " RES
    [[ $RES =~ ^[Yy]$ ]] && sh -c "$(curl -fsSL $2)"
}

web_script "Do you want to install 'dotfiles'? " https://raw.githubusercontent.com/Sebastian-Soto-M/dotfiles/master/.config/scripts/installs/i_dotfiles
web_script "Do you want to install 'suckless'? " https://raw.githubusercontent.com/Sebastian-Soto-M/dotfiles/master/.config/scripts/installs/i_suckless
web_script "Do you want to install 'zsh'?      " https://raw.githubusercontent.com/Sebastian-Soto-M/dotfiles/master/.config/scripts/installs/i_zsh
