#!/bin/sh
function web_script() {
    read -p "Do you wish to run the command from $1 [y/n]: " RES
    [[ $RES =~ ^[Yy]$ ]] && sh -c "$(curl -fsSL $1)"
}

web_script https://raw.githubusercontent.com/Sebastian-Soto-M/dotfiles/master/.config/scripts/installs/i_dotfiles
web_script https://raw.githubusercontent.com/Sebastian-Soto-M/dotfiles/master/.config/scripts/installs/i_suckless
web_script https://raw.githubusercontent.com/Sebastian-Soto-M/dotfiles/master/.config/scripts/installs/i_zsh
