#!/bin/sh
configs="dunst\nncspot\npicom\npolybar\nsxhkd\ntaskrc\ntmux\nzathura"
folders="blocks\ndmenu\ndwm\ndwm-status\nneovim\nscripts\nst\nsurf\nsxiv"
scripts="ask_pass\nautostart_dwm\nbookmark_browser\ndef_install\nedit menu\ninput_dm\ninput_validation_dm\npmanager_dm\nsearch_browser\nstartdwm"
shell="alias\np10k\nzshrc\nzshenv"
xorg="xinitrc\nxresources\nxres_dmenu\nxres_dwm\nxres_theme"

case "$(echo -e "${folders}\n${scripts}\n${configs}\n${shell}\n${xorg}" | dmenu -c -l 10)" in

    # terminal dirs
    autostart_dwm       ) st -e dash -c "nvim $XDG_DATA_HOME/dwm/autostart.sh"       ;;
    blocks              ) st -d "$XDG_CONFIG_HOME/dwmblocks"                         ;;
    dmenu               ) st -d "$XDG_CONFIG_HOME/dmenu"                             ;;
    dwm                 ) st -d "$XDG_CONFIG_HOME/dwm"                               ;;
    dwm-status          ) st -d "$XDG_CONFIG_HOME/dwm-status"                        ;;
    neovim              ) st -d "$XDG_CONFIG_HOME/nvim"                              ;;
    scripts             ) st -d "$SCRIPTS"                                           ;;
    st                  ) st -d "$XDG_CONFIG_HOME/st"                                ;;
    surf                ) st -d "$XDG_CONFIG_HOME/surf"                              ;;
    sxiv                ) st -d "$XDG_CONFIG_HOME/sxiv"                              ;;
    xres_theme          ) st -d "$XDG_CONFIG_HOME/X11/xresources"                    ;;

    # configs
    polybar             ) st -e dash -c "nvim $XDG_CONFIG_HOME/polybar/config"       ;;
    tmux                ) st -e dash -c "nvim $XDG_CONFIG_HOME/tmux/tmux.conf"       ;;
    ncspot              ) st -e dash -c "nvim $XDG_CONFIG_HOME/ncspot/config.toml"   ;;
    picom               ) st -e dash -c "nvim $XDG_CONFIG_HOME/picom/picom.conf"     ;;
    sxhkd               ) st -e dash -c "nvim $XDG_CONFIG_HOME/sxhkd/sxhkdrc"        ;;
    taskrc              ) st -e dash -c "nvim $TASKRC"                               ;;
    zathura             ) st -e dash -c "nvim $XDG_CONFIG_HOME/zathura/zathurarc"    ;;
    dunst               ) st -e dash -c "nvim $XDG_CONFIG_HOME/dunst/dunstrc"        ;;

    # zsh
    alias               ) st -e dash -c "nvim $ZDOTDIR/alias.zsh"                    ;;
    p10k                ) st -e dash -c "nvim $ZDOTDIR/.p10k.zsh"                    ;;
    zshrc               ) st -e dash -c "nvim $ZDOTDIR/.zshrc"                       ;;
    zshenv              ) st -e dash -c "nvim $HOME/.zshenv"                         ;;

    # scripts
    ask_pass            ) st -e dash -c "nvim $SCRIPTS/tools/ask_pass"               ;;
    bookmark_browser    ) st -e dash -c "nvim $SCRIPTS/dm/bookmark_browser"          ;;
    def_install         ) st -e dash -c "nvim $SCRIPTS/installs/def_install"         ;;
    input_dm            ) st -e dash -c "nvim $SCRIPTS/dm/input_dm"                  ;;
    input_validation_dm ) st -e dash -c "nvim $SCRIPTS/dm/input_validation_dm"       ;;
    pmanager_dm         ) st -e dash -c "nvim $SCRIPTS/dm/pmanager_dm"               ;;
    search_browser      ) st -e dash -c "nvim $SCRIPTS/dm/search_browser"            ;;
    startdwm            ) st -e dash -c "nvim $SCRIPTS/startdwm"                     ;;
    "edit menu"         ) st -e dash -c "nvim $SCRIPTS/dm/dotfiles_dm"               ;;

    # xorg
    xinitrc             ) st -e dash -c "nvim $XINITRC"                              ;;
    xresources          ) st -e dash -c "nvim $HOME/.Xresources"                     ;;
    xres_dwm            ) st -e dash -c "nvim $XDG_CONFIG_HOME/X11/xresources/dwm"   ;;
    xres_dmenu          ) st -e dash -c "nvim $XDG_CONFIG_HOME/X11/xresources/dmenu" ;;

    # default
    *                   )                                                            ;;
esac
