#!/bin/sh
chosen=$(echo -e "High\nMiddle\nLow" | dmenu -p "Redshift volume" -n 1 -c -l 3)
val=0
case "$chosen" in
"") ;;
High) val=5000 ;;
Middle) val=4500 ;;
Low) val=3800 ;;
esac
[[ $val != 0 ]] && redshift -P -O "${val}"
