#!/bin/sh
opts="all\npicom\nautostart\nstatus bar\nsxhkd\ndunst"

restart() {
    pkill -USR1 -x $1
    notify-send -u low "Restart executed" $1
}

case "$(echo -e "${opts}" | dmenu -c -l 10)" in
    all          ) restart "picom" & restart "dunst" & pkill autostart.sh ~/.local/share/dwm/autostart.sh & restart "sxhkd"                                                 ;;
    autostart    ) pkill autostart.sh ~/.local/share/dwm/autostart.sh                                                                                                       ;;
    dunst        ) pkill dunst && dunst notify-send -u low "Low notification" && notify-send -u normal "Normal notification" && notify-send -u critical "High notification" ;;
    picom        ) restart "picom"                                                                                                                                          ;;
    sxhkd        ) restart "sxhkd"                                                                                                                                          ;;
    "status bar" ) kill -9 $(pgrep -f "dwm_status")  && dwm_status                                                                                                          ;;
    *            )                                                                                                                                                          ;;
esac
