#!/bin/sh

choices="ArchWiki\nGitHub\nGoogle\nYouTube"
chosen=$(echo -e "$choices" | dmenu -p "Search Engines" -c -l 10)
w=""
case "$chosen" in
    ""       )                                                   ;;
    ArchWiki ) w="https://wiki.archlinux.org/index.php/"         ;;
    GitHub   ) w="https://www.github.com/search?q="              ;;
    Google   ) w="https://www.google.com/search?q="              ;;
    YouTube  ) w="https://www.youtube.com/results?search_query=" ;;
esac
[ ! -z "$w" ] && firefox "${w}$(input_dm $chosen)"
